### ISSUE TITLE
Missing ChunkBy

### ISSUE THREAD

**Issue by kingsleyh** [Dicebot/mood#16]
I forked and tried to run dub build on OSX DMD64 D Compiler v2.067.0 and got this:

Electron:mood kings$ dub build
Target vibe-d 0.7.24 is up to date. Use --force to rebuild.
Building mood 1.0.0+commit.2.g905fc78 configuration "application", build type debug.
Compiling using dmd...
Compiling diet template 'pages/new_post.dt'...
Compiling diet template 'pages/index.dt'...
blocks/aside.dt(9): Error: no property 'chunkBy' for type 'const(BlogPost[])'
../../../.dub/packages/vibe-d-0.7.24/source/vibe/templ/diet.d(51): Error: template instance mood.rendering.html.renderIndex.compileDietFileIndent!("pages/index.dt", 0, posts, last_posts) error instantiating
source/mood/rendering/html.d(23):        instantiated from here: compileDietFile!("pages/index.dt", posts, last_posts)
Compiling diet template 'pages/single_post.dt'...
blocks/aside.dt(9): Error: no property 'chunkBy' for type 'const(BlogPost[])'
../../../.dub/packages/vibe-d-0.7.24/source/vibe/templ/diet.d(51): Error: template instance mood.rendering.html.renderSinglePost.compileDietFileIndent!("pages/single_post.dt", 0, post, last_posts) error instantiating
source/mood/rendering/html.d(37):        instantiated from here: compileDietFile!("pages/single_post.dt", post, last_posts)
FAIL .dub/build/application-debug-posix.osx-x86_64-dmd_2067-7BCF6E16230B5189528000D71F90B5DD/ mood executable
Error executing command build: dmd failed with exit code 1.

**Comment by kingsleyh** [comment]
if I remove the code that does the chunking in blocks/aside.dt(9): Error: no property 'chunkBy' for type 'const(BlogPost[])' then mood starts up but as soon as I hit https://localhost:8080 it dies with no message I can see.

Electron:mood kings$ dub 
Target vibe-d 0.7.24 is up to date. Use --force to rebuild.
Building mood 1.0.0+commit.2.g905fc78 configuration "application", build type debug.
Compiling using dmd...
Compiling diet template 'pages/new_post.dt'...
Compiling diet template 'pages/index.dt'...
Compiling diet template 'pages/single_post.dt'...
Linking...
Running ./mood 
Preparing blog post data
Looking for blog post sources at ./generated/md/
0 posts loaded
Listening for HTTPS requests on ::1:8080
Listening for HTTPS requests on 127.0.0.1:8080
Error executing command run: Program exited with code -11

**Comment by Dicebot** [comment]
Are you using latest master version? I have recently added compatibility with older frontends (chunkby issue) - https://github.com/Dicebot/mood/commit/905fc78fa9c00e13acfbe9e0d64af4e98778470a
Will tag 1.0.1 with that soonish.

**Comment by Dicebot** [comment]
I can reproduce the crash, will create separate issue for that : https://github.com/Dicebot/mood/issues/17

**Comment by kingsleyh** [comment]
I have tried again on my other osx laptop and mood started up ok and was browsable on a later minor version of dmd:

DMD64 D Compiler v2.067.1

$ dub
Target vibe-d 0.7.24 is up to date. Use --force to rebuild.
Target mood 1.0.0+commit.2.g905fc78 is up to date. Use --force to rebuild.
Running ./mood 
Preparing blog post data
Looking for blog post sources at ./generated/md/
0 posts loaded
Listening for HTTPS requests on ::1:8080
Listening for HTTPS requests on 127.0.0.1:8080

**Comment by kingsleyh** [comment]
When I ran it again it started to die now:

$ dub run
Target vibe-d 0.7.24 is up to date. Use --force to rebuild.
Target mood 1.0.0+commit.2.g905fc78 is up to date. Use --force to rebuild.
Running ./mood 
Preparing blog post data
Looking for blog post sources at ./generated/md/
0 posts loaded
Listening for HTTPS requests on ::1:8080
Listening for HTTPS requests on 127.0.0.1:8080
Error executing command run:
Program exited with code -11

**Comment by Dicebot** [comment]
Is the last crash with 2.067 too or 2.068? Can be another manifestation of #17 ("Program exited with code -11" from dub usually means application has crashed)

**Comment by kingsleyh** [comment]
It was 2.067.1

**Comment by kingsleyh** [comment]
I just upgraded DMD to 2.068 and I have the same issue. It starts up and runs but after clicking around it crashes.
